import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { useQueryClient } from "@tanstack/react-query";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { useAccount } from "@/lib/account";
import { supabase } from "@/integrations/supabase/client";
import { lovable } from "@/integrations/lovable";
import type { AccountType } from "@/lib/account-rules";
export const Route = createFileRoute("/login")({head:()=>({meta:[{title:"Log in — SAC Community"},{name:"description",content:"Sign in or create your personal or business SAC Community account."},{property:"og:title",content:"Log in — SAC Community"},{property:"og:description",content:"Sign in and join the SAC Community."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"}]}),component:LoginPage});
function LoginPage(){
 const {user,loading}=useAccount(); const navigate=Route.useNavigate();const queries=useQueryClient();
 const [signup,setSignup]=useState(false);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [accountType,setAccountType]=useState<AccountType>('personal');
 useEffect(()=>{if(user&&!loading){void (async()=>{const pending=sessionStorage.getItem('sac-account-type');if(pending==='business'||pending==='personal'){const {error}=await supabase.rpc('set_account_type',{account_type:pending});if(error){setMessage(error.message);return;}sessionStorage.removeItem('sac-account-type');await queries.invalidateQueries({queryKey:['account-type']});}void navigate({to:'/explore',replace:true});})();}},[user,loading,navigate,queries]);
 const submit=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);setMessage('');const f=new FormData(e.currentTarget);const email=String(f.get('email'));const password=String(f.get('password'));try{if(signup){sessionStorage.setItem('sac-account-type',accountType);const {data,error}=await supabase.auth.signUp({email,password,options:{emailRedirectTo:window.location.origin,data:{full_name:String(f.get('name'))}}});if(error)throw error;if(!data.session)setMessage('Check your email to confirm your account, then log in.');}else{const {error}=await supabase.auth.signInWithPassword({email,password});if(error)throw error;}}catch(e){setMessage(e instanceof Error?e.message:'Could not log in.');}finally{setBusy(false);}};
 return <div className="min-h-screen bg-ink px-5 pb-16 pt-28 text-ink-foreground"><div className="mx-auto max-w-sm"><h1 className="font-display text-4xl">{signup?'Create account':'Log in'}</h1><form onSubmit={submit} className="mt-6 space-y-4">{signup&&<label className="block text-sm">Display name<Input name="name" required className="mt-1"/></label>}<label className="block text-sm">Email<Input name="email" type="email" autoComplete="email" required className="mt-1"/></label><label className="block text-sm">Password<Input name="password" type="password" minLength={8} autoComplete={signup?'new-password':'current-password'} required className="mt-1"/></label>{signup&&<fieldset><legend className="mb-2 text-sm">Account type</legend><div className="grid grid-cols-2 gap-2">{(['personal','business'] as const).map(t=><Button type="button" key={t} variant={accountType===t?'default':'outline'} aria-pressed={accountType===t} onClick={()=>setAccountType(t)} className="capitalize">{t}</Button>)}</div></fieldset>}{message&&<p role="status" className="text-sm">{message}</p>}<Button disabled={busy} className="w-full">{busy?'Please wait…':signup?'Create account':'Log in'}</Button></form><Button variant="outline" className="mt-3 w-full" onClick={async()=>{if(signup)sessionStorage.setItem('sac-account-type',accountType);const result=await lovable.auth.signInWithOAuth('google',{redirect_uri:window.location.origin+'/login'});if(result.error)setMessage(String(result.error.message));}}>Continue with Google</Button><Button variant="link" className="mt-3 w-full" onClick={()=>{setSignup(!signup);setMessage('');}}>{signup?'Already have an account? Log in':'Create an account'}</Button><Button asChild variant="link" className="w-full"><Link to="/explore">Back to Explore</Link></Button></div></div>;
}
