CREATE TABLE public.profiles (id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE, username text NOT NULL UNIQUE, full_name text NOT NULL DEFAULT '', bio text NOT NULL DEFAULT '', location text NOT NULL DEFAULT '', avatar_url text);
GRANT SELECT, UPDATE ON public.profiles TO authenticated; GRANT ALL ON public.profiles TO service_role;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY profiles_read_own ON public.profiles FOR SELECT TO authenticated USING (id = auth.uid());
CREATE POLICY profiles_update_own ON public.profiles FOR UPDATE TO authenticated USING (id = auth.uid()) WITH CHECK (id = auth.uid());
CREATE TABLE public.user_roles (user_id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE, role text NOT NULL DEFAULT 'personal' CHECK (role IN ('personal','business')));
GRANT SELECT ON public.user_roles TO authenticated; GRANT ALL ON public.user_roles TO service_role;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;
CREATE POLICY role_read_own ON public.user_roles FOR SELECT TO authenticated USING (user_id = auth.uid());
CREATE FUNCTION public.create_account_profile() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$ BEGIN INSERT INTO public.profiles(id,username,full_name) VALUES (NEW.id, 'user_' || replace(NEW.id::text,'-',''), coalesce(NEW.raw_user_meta_data->>'full_name','')); INSERT INTO public.user_roles(user_id,role) VALUES (NEW.id,'personal'); RETURN NEW; END; $$;
CREATE TRIGGER on_account_signup AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.create_account_profile();
CREATE FUNCTION public.set_account_type(account_type text) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$ BEGIN IF auth.uid() IS NULL THEN RAISE EXCEPTION 'Sign in required'; END IF; IF account_type NOT IN ('personal','business') THEN RAISE EXCEPTION 'Invalid account type'; END IF; UPDATE public.user_roles SET role = account_type WHERE user_id = auth.uid(); END; $$;
REVOKE ALL ON FUNCTION public.set_account_type(text) FROM PUBLIC, anon; GRANT EXECUTE ON FUNCTION public.set_account_type(text) TO authenticated;
CREATE TABLE public.community_content (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE, kind text NOT NULL CHECK (kind IN ('post','reel','tweet','event','ticket')), title text NOT NULL DEFAULT '', caption text NOT NULL DEFAULT '', media text[] NOT NULL DEFAULT '{}', city text NOT NULL DEFAULT '', event_date timestamptz, price numeric NOT NULL DEFAULT 0 CHECK (price >= 0), event_id uuid REFERENCES public.community_content(id), created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT, INSERT, DELETE ON public.community_content TO authenticated; GRANT ALL ON public.community_content TO service_role;
ALTER TABLE public.community_content ENABLE ROW LEVEL SECURITY;
CREATE POLICY content_read ON public.community_content FOR SELECT TO authenticated USING (true);
CREATE POLICY content_create ON public.community_content FOR INSERT TO authenticated WITH CHECK (user_id = auth.uid() AND (kind IN ('post','reel','tweet') OR EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = auth.uid() AND role = 'business')) AND (kind <> 'ticket' OR EXISTS (SELECT 1 FROM public.community_content e WHERE e.id = event_id AND e.user_id = auth.uid() AND e.kind = 'event')));
CREATE POLICY content_delete_own ON public.community_content FOR DELETE TO authenticated USING (user_id = auth.uid());
CREATE INDEX community_content_created ON public.community_content(created_at DESC);